### ISSUE TITLE
Incompatibility with JPype 0.7.2

### ISSUE THREAD

**Issue by dqd** [baztian/jaydebeapi#130] opened 2020-03-06 13:33 UTC
It seems that JayDeBeApi stopped to work after upgrading to JPype 0.7.2. When I try to connect to a database using the `jaydebeapi.connect` function, I get this error:

```
[...]
  File "/home/dqd/.local/lib/python3.5/site-packages/jaydebeapi/__init__.py", line 401, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/home/dqd/.local/lib/python3.5/site-packages/jaydebeapi/__init__.py", line 198, in _jdbc_connect_jpype
    for i in types.__javaclass__.getClassFields():
AttributeError: type object 'java.sql.Types' has no attribute '__javaclass__'
```

When I downgrade to JPype 0.7.1, everything works correctly again.

**Comment by dqd** [comment] 2020-03-06 13:45
Reading in the JPype 0.7.2 changelog (released at 29th of February 2020):

> All exposed internals have been replaced with CPython implementations thus symbols `__javaclass__`, `__javavalue__`, and `__javaproxy__` have been removed.

(See this commit: https://github.com/jpype-project/jpype/commit/09f6130ad691a20abd4247d47f1d813ea1057ed9)

**Comment by jdgwf** [comment] 2020-03-10 15:21
Just piping in that I'm seeing the same issue...
`Traceback (most recent call last):
  File "new-hours-upload.py", line 25, in <module>
    conn = jaydebeapi.connect(
  File "/usr/local/lib/python3.8/dist-packages/JayDeBeApi-1.1.2-py3.8.egg/jaydebeapi/__init__.py", line 401, in connect
  File "/usr/local/lib/python3.8/dist-packages/JayDeBeApi-1.1.2-py3.8.egg/jaydebeapi/__init__.py", line 198, in _jdbc_connect_jpype
AttributeError: type object 'java.sql.Types' has no attribute '__javaclass__'
`

**Comment by talktotyagi** [comment] 2020-03-22 22:57
I am getting the same error.

As mentioned earlier, when I tried to revert back to jpype to 0.7.1, I started getting new error:

c:\Python_Netezza>pip install jpype1==0.7.1
Collecting jpype1==0.7.1
  Using cached JPype1-0.7.1-cp37-cp37m-win_amd64.whl (1.4 MB)
Installing collected packages: jpype1
  Attempting uninstall: jpype1
    Found existing installation: JPype1 0.7.2
    Uninstalling JPype1-0.7.2:
      Successfully uninstalled JPype1-0.7.2
Successfully installed jpype1-0.7.1

c:\Python_Netezza>python Netezza.py
v_log_directory: C:\Python_Netezza\logs
Success



url : jdbc:netezza://STNPSMS.sherwin.com:5480/SNOWFLAKE:user=RO_SITPRAA;password=uNupOXNekKAC
Connection String: jdbc:netezza://STNPSMS.sherwin.com:5480/SNOWFLAKE
jdbc_driver_loc: C:\Python_Netezza\nzjdbc.jar
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "Netezza.py", line 94, in <module>
    conn = jaydebeapi.connect(jclassname=jdbc_driver_name, url=connection_string, driver_args={'user': dsn_uid, 'password': dsn_pwd}, jars=jdbc_driver_loc)
  File "C:\Users\axt405\AppData\Local\Programs\Python\Python37\lib\site-packages\jaydebeapi\__init__.py", line 381, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "C:\Users\axt405\AppData\Local\Programs\Python\Python37\lib\site-packages\jaydebeapi\__init__.py", line 159, in _jdbc_connect_jpype
    import jpype
  File "C:\Users\axt405\AppData\Local\Programs\Python\Python37\lib\site-packages\jpype\__init__.py", line 17, in <module>
    import _jpype
ImportError: numpy.core.multiarray failed to import

c:\Python_Netezza>

Any help appriciated.

**Comment by dqd** [comment] 2020-03-22 23:07
@talktotyagi It seems that you need an up-to-date version of the numpy library. You can obtain it from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

**Comment by talktotyagi** [comment] 2020-03-22 23:30
Thanks so much. I was missing numpy. Just installed it.

After installing numpy: I still get this error:

JVM PATH:  C:\Program Files\Java\jre1.8.0_221\bin\server\jvm.dll
Classpath :  C:\Python_Netezza\nzjdbc.jar
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="New Oracle"
Traceback (most recent call last):
  File "Netezza.py", line 94, in <module>
    conn = jaydebeapi.connect(jclassname=jdbc_driver_name, url=connection_string, driver_args={'user': dsn_uid, 'password': dsn_pwd}, jars=jdbc_driver_loc)
  File "C:\Users\axt405\AppData\Local\Programs\Python\Python37\lib\site-packages\jaydebeapi\__init__.py", line 388, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "C:\Users\axt405\AppData\Local\Programs\Python\Python37\lib\site-packages\jaydebeapi\__init__.py", line 179, in _jdbc_connect_jpype
    jpype.startJVM(jvm_path, *args, convertStrings=False)
  File "C:\Users\axt405\AppData\Local\Programs\Python\Python37\lib\site-packages\jpype\_core.py", line 227, in startJVM
    _jpype.startup(jvmpath, tuple(args), ignoreUnrecognized, convertStrings)
RuntimeError: java.lang.ClassNotFoundException: org.jpype.Utility


So that you know, here are various packages and their versions:

c:\Python_Netezza>pip freeze
asn1crypto==1.3.0
azure-common==1.1.25
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
boto3==1.11.17
botocore==1.14.17
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
cx-Oracle==7.3.0
docutils==0.15.2
idna==2.9
ijson==2.6.1
JayDeBeApi==1.1.1
jmespath==0.9.5
JPype1==0.7.1
numpy==1.18.2
oscrypto==1.2.0
pycparser==2.20
pycryptodomex==3.9.7
PyJWT==1.7.1
pyOpenSSL==19.1.0
python-dateutil==2.8.1
pytz==2019.3
requests==2.23.0
s3transfer==0.3.3
six==1.14.0
snowflake-connector-python==2.2.2
urllib3==1.25.8


Thanks in advance.

**Comment by dqd** [comment] 2020-03-23 07:00
@talktotyagi I see this error for the first time. Maybe try to downgrade to JPype 0.7.0, as described here: https://github.com/jpype-project/jpype/issues/573

**Comment by Thrameos** [comment] 2020-05-15 12:11
I am getting really tired of having my package pinned to old versions because of this package.  This package appears to be abandoned and making the users use old and buggy versions of JPype is not helpful to the community.   When someone accepts the answer "Just pin to an old buggy version" as acceptable answer on StackoverFlow, I cringe.  

I have written an alpha version replacement for this package.  Please join the discussion at jpype-project/jpype#744 could be made into a suitable replacement for this package.  It is not a drop in replacement as some items were exposed in a different way.  Unfortunately, an LGPL library is not license compatible with Apache 2 as far as I am aware, to this work was done from scratch.  My decision to complete it will depend in part on community interest.  If we can work out enough of the bugs to be usable then I will try to include it in JPype 0.8.  Otherwise it will slip towards later releases.

@dqd @khangp0000 @FeatCrush @dshen51 @cgivre  Are you interested in helping craft a suitable replacement?

**Comment by cgivre** [comment] 2020-05-15 12:55
@Thrameos 
I'd be happy to help. This issue has effectively blocked some work that I was working on to create a JDBC version of the Drill SqlAlchemy dialect, and possibly a generic JDBC dialect for that as well.  You can email me at cgivre(at)apache.org and I'm happy to discuss further.

**Comment by Thrameos** [comment] 2020-05-20 18:46
I have the first cut of the JayDeBeAPI replacement on the PR list at JPype.  If anyone wants to give it some alpha tests and post to issues to the PR it would be helpful.   Also having someone do popcorn gallery review of the documentation would be nice.

**Comment by cgivre** [comment] 2020-05-20 18:47
@Thrameos 
I'll take a look over the weekend.  Thanks for doing this!

**Comment by pbuxtonccuk** [comment] 2020-05-21 13:31
@Thrameos  looking forward to this replacement, because I don't like having to force to an old version of JPype.  Certainly my people in charge of the CI process don't like it, because they have a piprot section in the deployment path, so of course it fails to pass beyond because of forcing JPype 0.6.x

**Comment by Thrameos** [comment] 2020-05-21 15:14
@pbuxtonccuk Thanks for the interest.  If you would like to contribute then now is the time as JPype 0.8.0 is launching in June and I need get the replacement API solid by the release so it can ship it or it will end up falling back to the September update.  Recommend contributions (any of the following):

- Download the documentation attached to the PR and see what is there, missing, and needs fixing.
- Try the PR as a replacement on a JayDeBeAPI to see if will be a suitable replacement.
- Contribute a test case for an IN/OUT or OUT callproc so that the coverage can reach 100%
- Contribute a test case for features of H2 or HSQLDB as I don't really know much about databases so I was stretching my limits to create test cases.
- Comment on the names of classes functions and methods, as once it is released names will be stuck.
- Submit a code review on anything that you don't like or needs improving.

**Comment by baztian** [comment] 2020-05-22 19:57
Should be fixed with #135. Can you please verify?

**Comment by pbuxtonccuk** [comment] 2020-05-23 20:18
Hi @baztian 

I can confirm that at least in my dev environment, everything seems to work ok with JPype 0.7,5

I won't be able to check in the prod environment until Tuesday  (k8s on AWS) due to having to liaise with work colleagues (Monday is a public hol in the UK)

I see no reason why it should not work though.

**Comment by dclong** [comment] 2020-05-24 07:05
@baztian I can confirm that the issue is fixed in the latest version of JayDeBeApi (with JPype 0.7.5). Thank you very much for your hard work!

**Comment by pbuxtonccuk** [comment] 2020-05-24 11:14
@Bastian I can also confirm it solves the issue.  Many thanks for your effort here.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by baztian** [comment] 2020-05-25 14:33
Thanks guys for letting me know! (Would be nice if the jpype maintainers could adhere to semantic versioning. A patchlevel change should not introduce backward incompatibilities)

**Closed by baztian** 2020-05-25 14:33 UTC

**Comment by Thrameos** [comment] 2020-05-25 15:35
Sorry.  Unfortunately the transition from 0.7 to 0.8 has been unusually challenging.  There were a number of difficult decisions that were required due to bad contracts and a bad dependency with numpy.   However, I would point out that ``class_`` has been in since place 0.7.0 and thus we have not changed the public contracts except in cases were the public behavior was unusable. Until the core rewrite is complete (which I have been working on solidly for 2 years) any private variable is subject to change.

Did you happen to check if the ``class_`` method works on all of the 0.7 series?  I am not sure if "old_jpype" chck is really necessary.

**Comment by baztian** [comment] 2020-05-25 18:10
Following [semantic versioning](https://semver.org/) would ment that JPype 0.7 would actually been JPype 1.0.0. According to semver every release containing a backward incompatibile change would require a new major release. Every release containg one or more new features is a minor release and bugfix only releases are patchlevel.
Of course the JPype developers are free to choose whatever versioning they want. But I personally like the semantic versioning approach very much.

**Comment by baztian** [comment] 2020-05-25 18:13
@Thrameos you mean the `class_` method might work on jpype < 0.7 as well? old_jpype is for jpype versions before 0.7

**Comment by Thrameos** [comment] 2020-05-25 21:41
Sorry.  ``class_`` is just for 0.7 series on,  I misread.   Though is I read that section it appears to just be loading a table of types.  The safest thing for that type of code would like just to encode the table directly rather than using reflection as that works in all versions.   

I would be careful about using JPype versions prior to 0.7.   Every version leaked like sieve back then and it is unlikely that any long running program would not exhaust the memory.  It was fine for my usage where I just run short scripts that clean up by starting the next execution.   The 0.7 series is a bit better, but still has local reference frame leaks in some places hence just leaking slower.  I tuned up another leak just last week the needs to be dealt with.   The problem being that with two GC systems anything that is lost by one is immortal in the other and neither have very good tools for tracking the source.

As for the versioning system, I hope that we will have a real 1.0 release with actual type contracts that don't shift every time something changes such the semantic versioning is possible.   0.7 was just a half way point in the core rewrite because with 30k lines of code and one person it takes a year just to get through it all working nights and weekend.

Unfortunately, I have one more cycle of deprecations before the interface does not have a large number of regrettable things.  Most are completely undocumented misfeatures but if I was to up the version on each one of them that I find and correct it would have to be JPype 10.0.0 or larger.  The return contracts on JPype have been a nightmare as sometimes you get back the object type you pass in, sometimes you get a list, sometimes you get numpy array depending on what options it was compiled with all from the same method or even a String, Bool or None.  No matter how hard I try to maintain the same interface with that number of different behaviors, any bug fix would break some behavior silently.  Most had no tests to catch the fact a change was made and there was no code coverage to tell what as missing..   

I have been working to correct these defects.  Hence, the number of tests have grown from about  200 to 1200.   Coverage increased from 50% to 85%.  But I suspect to get all of the different interactions I would require another 600 more.  Every time I work through I have turned up another 20 interactions that do something unexpected.  I did a 30 pulls in 30 nights marathon in March to try to speed up the cycle.  Nothing has yet launched a copy of nethack, but I wouldn't put it past it.  Only then would semantic versioning start to make much sense, because then you actually can say what is there well enough to know something had been changed.

The maintainer @marscher is in charge of the release numbers so you can pitch the next release as 1.0 if you would like.  The numbering system was super.major.minor.patch but somehow it ended up as super.major.minor rather the normal major.minor.patch.  I don't know much about it as all of that was before my time.  We didn't even have a way to distinguish the released from the development copies until 2 months ago.  

The long plan is 2 more release cycles (about 1yr a piece) before we reach an actual stable point.  0.7 was just removing all of the regrettable string contracts, reflection stuff, and dealing with the tangled mess of the JNI memory interactions below the surface.   0.8 will be the next release with the backend finally mostly in Java and the Python front end in C, but will still have a bunch a bad contracts that were identified during 0.8 development cycle.   I don't feel comfortable removing them at 0.8 even though are mostly undocumented as until I have completed the Java to Python bridge code I can't be sure I have gotten them all.  0.8 is waiting on the last bad return contract and some shutdown/memory issues.  The next cycle will be dealing with all the internal changes required for the reverse bridge operation and corresponding byte assemblers needed for that task (hoping 6 months but still have to multiply by PI).  That will hopefully mean that at 0.9 I can just be correcting the missing pieces (implementing a Java class from Python, implementing a Python class from Java) and dealing with the GC loop paradox with a Java agent.
