### ISSUE TITLE
JayDeBeApi throws AttributeError: '_jpype.PyJPField' object has no attribute 'getStaticAttribute'

### ISSUE THREAD

**Issue by FlippieZ** [baztian/jaydebeapi#99] opened 2019-06-25 11:01 UTC
![Screenshot 2019-06-25 at 12 59 11](https://user-images.githubusercontent.com/34773194/60093182-15766c00-9749-11e9-8c4a-8138877d563e.png)

This error is returned when JayDeBeApi is used with the latest version of JPype (0.7.0).
With the previous version of JPype (0.6.3) no problem.

We use JayDeBeApi in our Databricks environment which installs by default the latest JPype version. Overriding this with 0.6.3 version solves the problem.

**Comment by rolweber** [comment] 2019-07-01 08:18
See section "Direct access to private fields" here:
https://github.com/jpype-project/jpype/issues/498

**Comment by grahamplace** [comment] 2019-07-03 03:54
Had the exact same issue — confirmed that pinning JPype (0.6.3) resolved for me as well.

**Comment by EmileSonneveld** [comment] 2019-07-28 20:52
Pinning JPype worked for me too ```pip install JPype1==0.6.3 --force-reinstall```

**Comment by dlbeswick** [comment] 2019-08-12 01:36
Hello, just a note that I've tested with current master (52a7da55f58d68ea379bdc95bf4c060648588994) and the issue is fixed for me.

**Comment by devarti** [comment] 2019-09-19 13:33
This - pip install JPype1==0.6.3 --force-reinstall worked.

**Comment by byrdman062** [comment] 2019-11-20 19:58
I am using Python 3.7 through Anaconda. I am unable to force the Jpype1 to 0.6.3. In Jupyter I get the following:


C:\Users\ab7y91\AppData\Local\Continuum\anaconda3\lib\site-packages\jpype1-0.7.0-py3.7-win-amd64.egg\jpype\_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
------------------------------------------
How do I change this within the module? Or is there another solution than the one mentioned above?

**Comment by tadtenacious** [comment] 2019-12-03 18:55
> I am using Python 3.7 through Anaconda. I am unable to force the Jpype1 to 0.6.3. In Jupyter I get the following:
> 
> ## C:\Users\ab7y91\AppData\Local\Continuum\anaconda3\lib\site-packages\jpype1-0.7.0-py3.7-win-amd64.egg\jpype_core.py:210: UserWarning:
> ## Deprecated: convertStrings was not specified when starting the JVM. The default
> behavior in JPype will be False starting in JPype 0.8. The recommended setting
> for new code is convertStrings=False. The legacy value of True was assumed for
> this session. If you are a user of an application that reported this warning,
> please file a ticket with the developer.
> How do I change this within the module? Or is there another solution than the one mentioned above?

I just ran into this too after installation, I was able to downgrade JPype1 this way:
`(venv) conda install -c conda-forge JPype1=0.6.3 --force-reinstall`
Seems to work now.

**Comment by bb14742** [comment] 2020-01-16 13:33
I used the “pip install JPype1==0.6.3 --force-reinstall” solution EmileSonneveld mentioned and it resolved my issue when I ran the code locally. However, I was trying to deploy my code to AWS Lambda using Jenkins. When I installed JayDeBeApi it relied on JPype1 and installed the 0.7.1 version. I then did a pip installed JPype1 version 0.6.3 using EmileSonneveld’s solution. When my code ran on Lambda it utilized the 0.7.1 version of JPype1. I was able to resolve this issue by putting the JPype1 install ahead of the JayDeBeApi install in my requirements.txt file as:
jpype1==0.6.3
JayDeBeApi

**Comment by manyi613** [comment] 2020-01-21 16:14
> I used the “pip install JPype1==0.6.3 --force-reinstall” solution EmileSonneveld mentioned and it resolved my issue when I ran the code locally. However, I was trying to deploy my code to AWS Lambda using Jenkins. When I installed JayDeBeApi it relied on JPype1 and installed the 0.7.1 version. I then did a pip installed JPype1 version 0.6.3 using EmileSonneveld’s solution. When my code ran on Lambda it utilized the 0.7.1 version of JPype1. I was able to resolve this issue by putting the JPype1 install ahead of the JayDeBeApi install in my requirements.txt file as:
> jpype1==0.6.3
> JayDeBeApi

i have same question, btw, i hope use python 3.8 in my test,but JayDeBeApi is not support as well, follow this issue. wish this problem sovled quickly.

**Comment by joseplar** [comment] 2020-01-31 21:55
Installed jaydebeapi two days ago, I had the same incompatibility issue with jpype 0.7.0, I had to downgrade jpype to 0.6.3. And jpype 0.6.3 is incompatible with latest python 3.8.1, so also had to downgrade python to 3.7.6.
These is what I had to install to make it work:
jaydebeapi                1.1.1
jpype1                    0.6.3
python                    3.7.6

**Comment by manyi613** [comment] 2020-02-03 13:06
> Installed jaydebeapi two days ago, I had the same incompatibility issue with jpype 0.7.0, I had to downgrade jpype to 0.6.3. And jpype 0.6.3 is incompatible with latest python 3.8.1, so also had to downgrade python to 3.7.6.
> These is what I had to install to make it work:
> jaydebeapi 1.1.1
> jpype1 0.6.3
> python 3.7.6

i ues this version on Windows 10 ,but i have fatal exception

```
Testing started at 21:05 ...
F:\pycharm\test37\Scripts\python.exe "F:\pycharm\PyCharm 2018.2.4\helpers\pycharm\_jb_pytest_runner.py" --target test_ldb.py::test_simple
Launching pytest with arguments test_ldb.py::test_simple in E:\workspace\test37

============================= test session starts =============================
platform win32 -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: E:\workspace\test37collected 1 item

test_ldb.py Windows fatal exception: access violation

Current thread 0x000023a4 (most recent call first):
  File "F:\pycharm\test37\lib\site-packages\jpype\_core.py", line 70 in startJVM
  File "F:\pycharm\test37\lib\site-packages\jaydebeapi\__init__.py", line 176 in _jdbc_connect_jpype
  File "F:\pycharm\test37\lib\site-packages\jaydebeapi\__init__.py", line 381 in connect
  File "E:\workspace\test37\test_ldb.py", line 12 in connect
  File "E:\workspace\test37\test_ldb.py", line 18 in test_simple
  File "F:\pycharm\test37\lib\site-packages\_pytest\python.py", line 167 in pytest_pyfunc_call
  File "F:\pycharm\test37\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 87 in <lambda>
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "F:\pycharm\test37\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "F:\pycharm\test37\lib\site-packages\_pytest\python.py", line 1445 in runtest
  File "F:\pycharm\test37\lib\site-packages\_pytest\runner.py", line 134 in pytest_runtest_call
  File "F:\pycharm\test37\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 87 in <lambda>
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "F:\pycharm\test37\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "F:\pycharm\test37\lib\site-packages\_pytest\runner.py", line 210 in <lambda>
  File "F:\pycharm\test37\lib\site-packages\_pytest\runner.py", line 237 in from_call
  File "F:\pycharm\test37\lib\site-packages\_pytest\runner.py", line 210 in call_runtest_hook
  File "F:\pycharm\test37\lib\site-packages\_pytest\runner.py", line 185 in call_and_report
  File "F:\pycharm\test37\lib\site-packages\_pytest\runner.py", line 99 in runtestprotocol
  File "F:\pycharm\test37\lib\site-packages\_pytest\runner.py", line 84 in pytest_runtest_protocol
  File "F:\pycharm\test37\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 87 in <lambda>
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "F:\pycharm\test37\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "F:\pycharm\test37\lib\site-packages\_pytest\main.py", line 271 in pytest_runtestloop
  File "F:\pycharm\test37\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 87 in <lambda>
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "F:\pycharm\test37\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "F:\pycharm\test37\lib\site-packages\_pytest\main.py", line 247 in _main
  File "F:\pycharm\test37\lib\site-packages\_pytest\main.py", line 197 in wrap_session
  File "F:\pycharm\test37\lib\site-packages\_pytest\main.py", line 240 in pytest_cmdline_main
  File "F:\pycharm\test37\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 87 in <lambda>
  File "F:\pycharm\test37\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "F:\pycharm\test37\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "F:\pycharm\test37\lib\site-packages\_pytest\config\__init__.py", line 93 in main
  File "F:\pycharm\PyCharm 2018.2.4\helpers\pycharm\_jb_pytest_runner.py", line 31 in <module>
```

**Comment by hunnifer** [comment] 2020-02-19 23:40
In the def of  `_jdbc_connect_jpype` within the `__init__ ` method, there used to be code to establish the version of jpype.  If it was "old" (pre 0.7), the method getStaticAttribute was used to make a types map, otherwise (post v0.7)  `__get__` was used.  Restoring this code lets me get on with my database linkup:
```

    if hasattr(jpype, '__version__'):
        try:
            ver_match = re.match('\d+\.\d+', jpype.__version__)
            if ver_match:
                jpype_ver = float(ver_match.group(0))
                if jpype_ver < 0.7:
                    old_jpype = True
                else:
                    old_jpype = False
        except ValueError:
            pass

types_map = {}
        for i in types.__javaclass__.getClassFields():
            if old_jpype:
                types_map[i.getName()] = i.getStaticAttribute()
            else:
                types_map[i.getName()] = i.__get__(i)
        _init_types(types_map)
'''

**Comment by jmskarda** [comment] 2020-02-27 20:46
@hunnifer's [solution](https://github.com/baztian/jaydebeapi/issues/99#issuecomment-588531733) worked for me too.  However, instead of restoring the whole code block I just corrected the incorrect call.  Should work fine unless JPype ver < 0.7.

\jaydebeapi\\__init__.py (~ Line 183)
```
            # types_map[i.getName()] = i.getStaticAttribute()  # Original incorrect call
            types_map[i.getName()] = i.__get__(i) # Corrected call
```

**Comment by gantir** [comment] 2020-03-06 18:27
> This - pip install JPype1==0.6.3 --force-reinstall worked.

I too got things working with this workaround. Is a proper fix for this issue available?

**Comment by srmds** [comment] 2020-03-24 21:18
Forcing a reinstall of the old version `JPype1==0.6.3` is _not_ an option for me, because JPype1 0.7.0 contain essential fixes. Therefore, would like to have the compatibility of JayDeBeApi with JPype version `>0.7.*`

**Comment by baztian** [comment] 2020-05-22 19:59
Should be fixed in the current version

**Closed by baztian** 2020-05-22 19:59 UTC
